CREATE TABLE COMPANY(
    ID int(4) NOT NULL PRIMARY KEY,
    NAME str,
    EMPLOYEES int
);

INSERT INTO COMPANY
VALUES("1","Adobe","28085");

INSERT INTO COMPANY
VALUES("2","Flipkart","35543");

INSERT INTO COMPANY
VALUES("3","Amazon","1089");

INSERT INTO COMPANY
VALUES("4","Paytm","9982");

INSERT INTO COMPANY
VALUES("5","BookMyShow","5589");

INSERT INTO COMPANY
VALUES("6","Oracle","4003");

INSERT INTO COMPANY
VALUES("7","NIIT","57782");

INSERT INTO COMPANY
VALUES("8","Samsung","2000");

INSERT INTO COMPANY
VALUES("9","TCS","10046");

INSERT INTO COMPANY
VALUES("10","Wipro","3500");

SELECT ID FROM COMPANY
WHERE EMPLOYEES> 10000
ORDER BY ID ASC;
